development:
  adapter: postgresql
  database: lesson3
  username: ivan
  password: 3022666
test:
  adapter: postgresql
  database: lesson3_test
  username: ivan
  password: 3022666
production:
  adapter: postgresql
  database: lesson3
  username: ivan
  password: 3022666