development:
  adapter: postgresql
  database: courses
  username: ivan
  password: 3022666
test:
  adapter: postgresql
  database: courses_test
  username: ivan
  password: 3022666
production:
  adapter: postgresql
  database: courses
  username: ivan
  password: 3022666